server:
    port: 8080
    servlet:
       context-path: /spider


#mybatis配置
mybatis:
  typeAliasesPackage: com.ng.spider.bean.entity
  mapperLocations: classpath*:mapper/*.xml
  config-locations: classpath*:mybatis-config.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

logging:
      level:
       com.ng.spider.dao: debug

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
           multipart:
              max-file-size: 20MB
              max-request-size: 20MB
  application:
    name: spider

debug: false

